#pragma once
#include <Arduino.h>

namespace Button {
    enum class Event : uint8_t {
        NONE,
        PRESS,
        RELEASE,
        LONG_PRESS,
    };
    void begin();
    void update(uint32_t nowMs);

    // Returns the event generated by the most recent update(), if any.
    // Consumes it — calling again before the next update() returns NONE.
    Event getEvent();

    bool isPressed();
}